"""
Script: gmsh_topo_elevation.py
Author: Mateo Guamán Cueva
Description: Bypasses the CGNS high-order export limitation from commercial meshers (e.g., ANSA).
It uses the Gmsh Python API to read an Order 2 .cgns mesh, reconstructs the physical groups 
(boundary conditions), elevates the topological order to 4 by injecting nodes, and exports 
it as a native .msh file for PyHOPE ingestion.
"""

import gmsh
import sys

# Initialize the Gmsh API
gmsh.initialize()

# Load the original mesh (generated by ANSA)
input_mesh = "ESFERA_HEXAS_g2_v3p2.cgns"
print(f"Reading original mesh: {input_mesh}...")
gmsh.merge(input_mesh)

# Reconstruct physical groups to preserve PIDs / Boundary Conditions
# Note: The names must exactly match the PIDs defined in ANSA and PyHOPE's parameter.ini.
# 2D boundaries (surfaces)
gmsh.model.addPhysicalGroup(2, [2], name="Esfera")
gmsh.model.addPhysicalGroup(2, [3], name="Dominio_exterior")
gmsh.model.addPhysicalGroup(2, [5], name="Entrada")
gmsh.model.addPhysicalGroup(2, [4], name="Salida")
# 3D boundary (volume)
gmsh.model.addPhysicalGroup(3, [1], name="fluid")

# Elevate the topology to Order 4.
# Since no CAD file (STEP/IGES) is provided, Gmsh will simply inject 
# the necessary nodes into faces and edges, leaving them geometrically FLAT.
print("Injecting nodes to elevate to Order 4...")
gmsh.model.mesh.setOrder(4)

# Optimization is turned off due to high memory consumption on dense meshes
# gmsh.model.mesh.optimize("HighOrder")      

# Clean up the mesh to prevent connectivity issues
gmsh.model.mesh.removeDuplicateNodes()

# Save the new mesh.
# Exported as .msh (Gmsh native format) instead of .cgns to prevent PyHOPE crashes.
output_mesh = "ESFERA_HEXAS_g4_topo.msh"
gmsh.write(output_mesh)

gmsh.finalize()
print(f"Success! Mesh saved as {output_mesh}. Ready for PyHOPE.")
